name: Тестирование

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: autumn-library/workflows/.github/workflows/test.yml@oneunit
    with:
      os_versions: '["ubuntu-latest", "windows-latest"]'
